FROM elixir:1.12.0-alpine

RUN mix local.hex --force && \
    mix local.rebar --force && \
    mix archive.install hex phx_new --force && \
    mkdir -p /umbrella

COPY . /umbrella
ENV MIX_ENV dev

RUN cd /umbrella && \
    mix do deps.get, compile && \
    MIX_ENV=test mix do deps.get, compile

WORKDIR /umbrella
EXPOSE 4000
